### ISSUE TITLE
Toolbar should not be disabled in HTML mode

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-iOS-Editor#155]
title says it all

**Comment by bummytime** [comment]
>  Might be a good idea to move to 4.7 (ie: the release after the public release).

Full public release is now 4.8...pushing this to future because of complexity.

**Comment by thianhlu** [comment]
Moving this back into 4.8, we are gonna need to do this one

**Comment by meremagee** [comment]
for v1, going to enable richtext but leave media disabled. there's more complexity around implementing media since we've changed the flow with local placeholders.

we want the html editor to be able to be a fully functional replacement for folks partial to the legacy editor, but since it's 2+ clicks to add media on legacy editor currently, disabling media from html in the interim is not necessarily deprecating the experience. this should only be thought of as an interim solution as we prioritize other 4.8 blockers, and should be high priority for 4.9.

for now:
- show add media button disabled in html ui
- hit add media button > alert: need to switch to visual to add media

ultimately, preferred behavior would be:
- hit add media from html format bar
- go to photo library > select images
- see "uploading..." in nav bar
- insert remote url in img src

ux for switching modes during upload tbd: for now, blocked
