### ISSUE TITLE
Onboarding: cleanup ui

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#512]
modal on ios7, iphone 5s & ipad 2

![](https://cloudup.com/iNbxggOQCSp+)

**Comment by meremagee** [comment]
here's ipad2 https://cloudup.com/iwyxMX1KmW5

**Comment by bummytime** [comment]
Instead of creating a new issue, I'll just add this here. After upgrading I reopened the app which was restored on the new post screen for the editor:

![scaled screen shot 2015-01-28 at 2 46 37 pm](https://cloud.githubusercontent.com/assets/154014/5946606/b5aebf48-a6fc-11e4-9f2d-efde8126d909.png)

...the on-boarding displayed as expected, but I was unable to dismiss it. Trapped.

![giphy](https://cloud.githubusercontent.com/assets/154014/5946637/f08defee-a6fc-11e4-93f1-ad6534e7415f.gif)

**Comment by diegoreymendez** [comment]
@bummytime - That's scary.  Especially considering that the app may restore state in a different number of similar but different situations.

**Comment by bummytime** [comment]
@diegoreymendez I should add that I was able to minimize the QuickType bar and tap a corner of the dismiss button, but the average Joe may not know that.

**Comment by diegoreymendez** [comment]
@bummytime - Opened a separate issue for the editor state restoration madness.

**Comment by diegoreymendez** [comment]
Fixed.
