### ISSUE TITLE
The placeholder color is off.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS-Editor#515]
The placeholder color for the new visual editor seems to have changed.

May be related to [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/514#issuecomment-71980522), since the color change seems to come from [the same commit](https://github.com/wordpress-mobile/WordPress-iOS/commit/a5ec6aefc155a5f8dc10bd45ca860228add477a2).

**Comment by meremagee** [comment]
Looks pretty good against the original specs: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/325 so I'm adding *low priority* tag

**Comment by bummytime** [comment]
This commit: https://github.com/wordpress-mobile/WordPress-iOS-Editor/commit/45fa1fffa5d5d964fd035a348d42783fece979a7 may be the culprit here. When I check the previous commit out the placeholder color works. On this commit, it doesn't.

Seems like the ```color``` CSS value on ```div#zss_field_content.field``` is being set for some reason.

**Previous commit:**

![screen shot 2015-01-30 at 2 25 54 pm](https://cloud.githubusercontent.com/assets/154014/5988615/78ebad2c-a92d-11e4-94d5-4f93bc005345.png)

**https://github.com/wordpress-mobile/WordPress-iOS-Editor/commit/45fa1fffa5d5d964fd035a348d42783fece979a7 commit:**

![screen shot 2015-01-30 at 2 27 59 pm](https://cloud.githubusercontent.com/assets/154014/5988616/7ea2bc10-a92d-11e4-830e-046ceab9e71a.png)
