### ISSUE TITLE
onboarding: showing on top of the restored editor breaks the GUI.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS-Editor#548]
As reported by @bummytime [in this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/512).

This is how the onboarding tip looks after opening the app that restores on the editor.

![b5aebf48-a6fc-11e4-9f2d-efde8126d909](https://cloud.githubusercontent.com/assets/1836005/6089536/ffe0f124-ae42-11e4-9fcf-bdef7329f0a8.png)

**Comment by meremagee** [comment]
this can happen upon post restoration if update happens while app is closed & user is on a post _if the user has new editor enabled_. The catch, however, is that for these users (w/ editor enabled) we won't be showing onboarding (since they have editor).

that said, we do _crash_ the app if user doesn't have new editor > leaves app on legacy editor > app updates > user opens app. logged [here](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/560)

- should we reset app to my sites or reader upon upgrade & save anything in legacy > local draft?
- try to gracefully switch legacy > new editor if user restores state to editor after update? + collapse keyboard and overlay onboarding atop post?

**Comment by diegoreymendez** [comment]
The crash is resolved in [a different issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/560), so I'm leaving that out for now.

Are users who had previously enabled the editor seeing the onboarding tip?

**Comment by meremagee** [comment]
> Are users who had previously enabled the editor seeing the onboarding tip?

Nope! Thus, I think having fixed the crasher - which is the only flow through which I can think of to get the editor + onboarding - makes this issue null. Testing a couple of other things to make sure.

@diegoreymendez @bummytime - can you think of any ways to get here on which I'm blanking?

**Comment by meremagee** [comment]
given onboarding logic...
- show onboarding to users who do not have editor available
- never restore to legacy editor
- must dismiss onboarding to navigate to another page

a user should never get into a scenario where they see both onboarding & editor at the same time. closing.

**Comment by diegoreymendez** [comment]
Agreed.  Let's keep an eye out for this though.
