### ISSUE TITLE
CRASH: if update > restore to legacy editor

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#560]
100% repro (iphone5s, ios7)

log: https://cloudup.com/cTPz6BU5-fc

repro:
- install app pre-4.8
- create post in legacy editor (new editor setting is not enabled)
- leave app > go to hockey app
- install 4.8
- when 4.8 is complete, open beta app
- state restored to legacy editor post
- crash

cc @bummytime @diegoreymendez 

assuming we're trying to force onboarding/new editor & it's conflicting with state restoration

**Comment by meremagee** [comment]
Upon open after crash > dismiss alert to send crash report > see onboarding ui for ~1sec before it disappears

**Comment by diegoreymendez** [comment]
Thanks for the report.  Should be an easy fix.

**Comment by diegoreymendez** [comment]
It seems there's some strange problem with the legacy restoration code, when the new editor is enabled. In order to fix this issue in a secure manner I disabled the legacy editor restoration if the new editor should be used instead - the result is that the post will be saved as draft but the legacy editor window will not be restored and the app won't crash.

**Comment by diegoreymendez** [comment]
Fixed.
